clinic:
  host-name: my-doctor.com
  name: MyClinic
  specializations:
    specializationName:
      - surgeon
      - therapist
      - cardiologist
  hours:
    hourName:
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

  h2:
    console:
      enabled: true
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
logging:
  level:
    sql: debug