clinic:
  host-name: my-doctor.com
  name: MyClinic
  specializations:
    specializationName:
      - surgeon
      - therapist
      - cardiologist


  spring:
    h2:
      console:
        enabled: true
  logging:
    level:
      sql: debug





